services:
  - type: web
    name: market-research-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_wrapper:app --host 0.0.0.0 --port 8000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.5


